# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3848f6397b6655c5683a6fb052c4663fd6b9e185bc479abc6714b131ed446279a3eaeaa78501b61a898ab903bddcadd851a8253825a5eeff06f73b49e2176055

test:
  secret_key_base: cc43c0820c59c4d2c79caff182e861ef17defd577eb7695c11d5871019640a350d89988a91bcf45e268203c17f36657aa41cf0cbfe0f2caf7b4729ecc6149575

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
